# Generated by Django 2.1.1 on 2019-02-15 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.CharField(choices=[('C', 'Celena'), ('H', 'Vacation (paid)'), ('G', 'Unpaid Leave'), ('K', 'Katie'), ('P', 'Pete'), ('M', 'Melanie'), ('N', 'Nicole')], max_length=2)),
                ('child_name', models.CharField(max_length=256)),
                ('month_year', models.DateTimeField()),
                ('hours_spent', models.IntegerField()),
                ('hours_education', models.IntegerField()),
                ('hours_on_case', models.IntegerField()),
                ('continuing_edu', models.CharField(max_length=256)),
                ('miles_driven', models.FloatField()),
                ('face_advocate_sv_hours', models.IntegerField()),
                ('phone_advocate_sv', models.CharField(max_length=256)),
                ('other_volunteering', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
