# Generated by Django 2.1.1 on 2019-02-18 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20190218_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingform',
            name='month_year',
        ),
    ]
