# Generated by Django 2.1.2 on 2019-02-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_trackingform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingform',
            name='advocate',
            field=models.CharField(default='advocate', max_length=256),
            preserve_default=False,
        ),
    ]
