# Generated by Django 2.1.1 on 2019-03-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0007_trackingform_advocate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingform',
            name='supervisor',
            field=models.CharField(choices=[('enewcomer23@gmail.com', 'Celena'), ('H', 'Heidi'), ('G', 'Gail'), ('K', 'Katie'), ('P', 'Pete'), ('M', 'Melanie'), ('N', 'Nicole')], max_length=256),
        ),
    ]
