# Generated by Django 2.0.5 on 2019-05-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0011_auto_20190516_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingform',
            name='esignature',
            field=models.TextField(blank=True),
        ),
    ]
