# Generated by Django 2.0.5 on 2019-09-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0015_trackingform_advocate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingform',
            name='the_voice',
            field=models.CharField(default='No', max_length=256),
            preserve_default=False,
        ),
    ]
