# Generated by Django 2.0.5 on 2019-10-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0016_trackingform_the_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingform',
            name='hours_education',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='hours_on_case',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='hours_spent',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='miles_driven',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
