# Generated by Django 2.2.6 on 2020-05-18 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0018_auto_20191007_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingform',
            name='supervisor_signature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='signature_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
