# Generated by Django 2.1.1 on 2019-02-18 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_remove_trackingform_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingform',
            name='month',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
