# Generated by Django 2.1.1 on 2019-02-23 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_trackingform_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
