# Generated by Django 2.1.5 on 2019-03-09 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0009_auto_20190302_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingform',
            name='signature',
            field=models.CharField(default='signature', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingform',
            name='signature_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
