# Generated by Django 2.0.5 on 2019-05-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0012_trackingform_esignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingform',
            name='casa_volunteering',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='hours_education',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='hours_on_case',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='hours_spent',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='miles_driven',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
