# Generated by Django 2.0.5 on 2019-06-12 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0013_auto_20190529_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingform',
            name='casa_volunteering',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='supervisor',
            field=models.CharField(max_length=256),
        ),
    ]
