# Generated by Django 2.0.5 on 2019-10-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0017_auto_20191007_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingform',
            name='hours_education',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='hours_on_case',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='hours_spent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trackingform',
            name='miles_driven',
            field=models.FloatField(),
        ),
    ]
