# Generated by Django 2.2.6 on 2020-05-18 06:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0019_auto_20200518_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingform',
            name='supervisor_signature_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
